version: "3.9"

services:
  postgres:
    image: postgres:14.1
    container_name: postgres_container
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/DealMasterDbData/
      POSTGRES_PASSWORD: DealMasterPassword
      POSTGRES_USER: DealMasterUser
      POSTGRES_DB: DealMasterDb
    volumes:
      - ./Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  bot:
    build: .
    container_name: bot_container
    restart: unless-stopped
    depends_on:
      - postgres

  redirect_page:
    build: ./RedirectPageApp/
    container_name: redirect_page_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - bot